version: "3"

services:

  redis:
    image: redis
    container_name: "laravel_api_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql
    container_name: "laravel_api_mysql"
    ports:
      - "3306:3306"
    env_file:
      - ./docker/mysql/.env
    volumes:
      - dbdata:/var/lib/mysql
    
  front:
    image: abiosoft/caddy
    container_name: "laravel_api_front"
    environment:
      - CADDYPATH=/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - ./docker/caddy/caddyssl:/etc/caddycerts
     

  app:
    image: laravel_api_skeleton:build
    build: .
    container_name: "laravel_api_app"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    command: /usr/local/sbin/php-fpm --allow-to-run-as-root
